In [1]:
import numpy as np

In [ ]:
x_values = [1,4,5,2,4,7,8,4,6,1]
xx_values = [[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1]]
xxx_values = [[[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1]],[[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1]],[[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1],[1,4,5,2,4,7,8,4,6,1]]]
numpy_x_values = np.array(x_values)
numpy_xx_values = np.array(xx_values)
numpy_xxx_values = np.array(xxx_values)

In [2]:
zeros_array = np.zeros(5)
print(zeros_array)
ones_array = np.ones(10, dtype=int)
print(ones_array)
empty_array = np.empty(10)
print(empty_array)

[0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[            nan 0.00000000e+000 6.47930144e-312 2.02369289e-320
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [ ]:
numpy_range_array = np.arange(0, 10, dtype=int)
print(numpy_range_array)

In [ ]:
linspace_array = np.linspace(1, 10, 5)
print(linspace_array)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_matrix = np.array(matrix)
print(numpy_matrix)


In [ ]:
print(np.zeros((3,7)))

In [ ]:
some_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = some_array.reshape(2, 3)
print(reshaped_array)



In [ ]:
def f(x,y):
    return x* (y + 1)

some_matrix = np.fromfunction(f, (3,3))
print(some_matrix)

In [63]:
some_matrix = np.array([[1, 2, 3], [4, 2, 6], [7, 8, 9]])

print(some_matrix)


In [16]:
some_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
some_array[5:10] = [0, 0, 0, 0, 1]
print(some_array)
print(some_array[3:9])

[1 2 3 4 5 0 0 0 0 1]
[4 5 0 0 0 0]
[[1 2 3]
 [4 2 6]
 [7 8 9]]


In [21]:
some_matrix = np.array([[1, 4, 3], [4, 8, 6], [7, 2, 9]])
#limit values: any value greater or equal than 7 should be -1
some_matrix[some_matrix >= 7] = -1
print(some_matrix)

[[ 1  4  3]
 [ 4 -1  6]
 [-1  2 -1]]


In [ ]:


some_array = np.array([1, 2, 3, 4, 5])
result = some_array * 2
print(result)


In [24]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[1, 2], [3, 4], [5, 6]])
result = np.dot(matrix1, matrix2)
print(result)
result = matrix1.dot(matrix2)
print(result)
result = matrix1 @ matrix2
print(result)
result = matrix2 @ matrix1
print(result)


[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [29]:
some_array = np.array([1, 2, 3])
result = np.append(some_array, [4, 5, 6])
print(result)
result = np.insert(some_array, 1, [9,8])
print(result)
result = np.delete(some_array, 2)
print(result)

[1 2 3 4 5 6]
[1 9 8 2 3]
[1 2]


In [42]:
matrix = np.array([[1, 2, 3, 1], [4, 5, 6, 1]])
result = np.append(matrix, [[1,1,1,1]], axis=0)
print(result)
result = np.append(matrix, [[13], [13]], axis=1)
print(result)

SyntaxError: incomplete input (2948932109.py, line 7)